### ISSUE TITLE
[Feature Request] Saving instances

### ISSUE THREAD

**Issue by habmalnefrage** [Windows-Apps-Hub/UnitedSets#61] opened 2024-05-07 14:41 UTC
Hi,
Possibility to save instances including the added windows in each instance.
So that the instances with their windows could be closed and reopened with same status as before closed. 

Would also be helpful for windows updates when restarting windows.

thanks
best
berthold

**Comment by GetGet99** [comment] 2024-05-17 15:20
Duplicate of #53 . I'll close this issue. Please follow updates from that issue. Thanks!

**Closed by GetGet99** 2024-05-17 15:20 UTC
